In [29]:
import torch

x = torch.Tensor([5, 3])
y = torch.Tensor([2, 1])
x*y

tensor([10.,  3.])

In [30]:
x = torch.zeros([2, 5])
x

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [31]:
x.shape

torch.Size([2, 5])

In [32]:
y = torch.rand([2, 5])
y

tensor([[0.3917, 0.7291, 0.8621, 0.8796, 0.5517],
        [0.9250, 0.3091, 0.5598, 0.7830, 0.8097]])

In [33]:
y.shape

torch.Size([2, 5])

In [34]:
y = y.view([1, 10])

In [35]:
y

tensor([[0.3917, 0.7291, 0.8621, 0.8796, 0.5517, 0.9250, 0.3091, 0.5598, 0.7830,
         0.8097]])

In [36]:
y.shape

torch.Size([1, 10])

In [43]:
torch.cuda.device_count()

0

In [40]:
torch

<module 'torch' from '/home/aki/.local/lib/python3.10/site-packages/torch/__init__.py'>