In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

warnings.filterwarnings('ignore') 

In [17]:
import torch 

x = torch.rand(2, 2)
y = torch.rand(2, 2)

print(x)
print(y)

tensor([[0.5538, 0.0731],
        [0.5708, 0.6293]])
tensor([[0.9051, 0.5920],
        [0.6512, 0.0283]])


In [23]:
y.add_(x)
print(y)

tensor([[2.0127, 0.7383],
        [1.7929, 1.2870]])


In [24]:
x = torch.rand(5, 3)
y = torch.rand(10, 3)

x.view(15)

tensor([0.4059, 0.6461, 0.7666, 0.5791, 0.2170, 0.6043, 0.2774, 0.5609, 0.5124,
        0.4972, 0.4291, 0.9205, 0.0879, 0.8679, 0.1488])

In [27]:
y.view(30)

tensor([0.7050, 0.4281, 0.8881, 0.4770, 0.9802, 0.4816, 0.7467, 0.9507, 0.7683,
        0.4220, 0.6503, 0.5785, 0.7821, 0.2963, 0.7044, 0.3773, 0.5743, 0.9583,
        0.1831, 0.0684, 0.6315, 0.8138, 0.0367, 0.9421, 0.9448, 0.9367, 0.2518,
        0.6511, 0.8605, 0.1954])

In [30]:
torch.cuda.is_available()

False